name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        # Install project dependencies for proper import resolution
        pip install -r SphinxAI/requirements-runtime.txt || pip install -r SphinxAI/requirements.txt || true
        # Install additional dependencies that might be missing
        pip install pytest pytest-cov || true
    - name: Analysing the code with pylint
      run: |
        # Run pylint with more lenient settings for CI
        pylint $(git ls-files '*.py') --disable=import-error,no-member,too-many-arguments,too-many-locals,too-few-public-methods,missing-module-docstring,missing-class-docstring,missing-function-docstring,logging-fstring-interpolation,unexpected-keyword-arg,abstract-class-instantiated,trailing-whitespace --exit-zero
